/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CanchaRouteImport } from './routes/cancha'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as EliminarCuentaRouteImport } from './routes/eliminar-cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OlvideRouteImport } from './routes/olvide'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SeguridadRouteImport } from './routes/seguridad'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as VivoRouteImport } from './routes/vivo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CanchaRoute = CanchaRouteImport.update({
  id: '/cancha',
  path: '/cancha',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminarCuentaRoute = EliminarCuentaRouteImport.update({
  id: '/eliminar-cuenta',
  path: '/eliminar-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OlvideRoute = OlvideRouteImport.update({
  id: '/olvide',
  path: '/olvide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguridadRoute = SeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const VivoRoute = VivoRouteImport.update({
  id: '/vivo',
  path: '/vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cancha': typeof CanchaRoute
  '/chat': typeof ChatRoute
  '/contacto': typeof ContactoRoute
  '/equipo': typeof EquipoRoute
  '/eliminar-cuenta': typeof EliminarCuentaRoute
  '/login': typeof LoginRoute
  '/olvide': typeof OlvideRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset': typeof ResetRoute
  '/seguridad': typeof SeguridadRoute
  '/stats': typeof StatsRoute
  '/terminos': typeof TerminosRoute
  '/vivo': typeof VivoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cancha': typeof CanchaRoute
  '/chat': typeof ChatRoute
  '/contacto': typeof ContactoRoute
  '/equipo': typeof EquipoRoute
  '/eliminar-cuenta': typeof EliminarCuentaRoute
  '/login': typeof LoginRoute
  '/olvide': typeof OlvideRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset': typeof ResetRoute
  '/seguridad': typeof SeguridadRoute
  '/stats': typeof StatsRoute
  '/terminos': typeof TerminosRoute
  '/vivo': typeof VivoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cancha': typeof CanchaRoute
  '/chat': typeof ChatRoute
  '/contacto': typeof ContactoRoute
  '/equipo': typeof EquipoRoute
  '/eliminar-cuenta': typeof EliminarCuentaRoute
  '/login': typeof LoginRoute
  '/olvide': typeof OlvideRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset': typeof ResetRoute
  '/seguridad': typeof SeguridadRoute
  '/stats': typeof StatsRoute
  '/terminos': typeof TerminosRoute
  '/vivo': typeof VivoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cancha'
    | '/chat'
    | '/contacto'
    | '/equipo'
    | '/eliminar-cuenta'
    | '/login'
    | '/olvide'
    | '/privacidad'
    | '/reset'
    | '/seguridad'
    | '/stats'
    | '/terminos'
    | '/vivo'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cancha'
    | '/chat'
    | '/contacto'
    | '/equipo'
    | '/eliminar-cuenta'
    | '/login'
    | '/olvide'
    | '/privacidad'
    | '/reset'
    | '/seguridad'
    | '/stats'
    | '/terminos'
    | '/vivo'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cancha'
    | '/chat'
    | '/contacto'
    | '/equipo'
    | '/eliminar-cuenta'
    | '/login'
    | '/olvide'
    | '/privacidad'
    | '/reset'
    | '/seguridad'
    | '/stats'
    | '/terminos'
    | '/vivo'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CanchaRoute: typeof CanchaRoute
  ChatRoute: typeof ChatRoute
  ContactoRoute: typeof ContactoRoute
  EquipoRoute: typeof EquipoRoute
  EliminarCuentaRoute: typeof EliminarCuentaRoute
  LoginRoute: typeof LoginRoute
  OlvideRoute: typeof OlvideRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetRoute: typeof ResetRoute
  SeguridadRoute: typeof SeguridadRoute
  StatsRoute: typeof StatsRoute
  TerminosRoute: typeof TerminosRoute
  VivoRoute: typeof VivoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancha': {
      id: '/cancha'
      path: '/cancha'
      fullPath: '/cancha'
      preLoaderRoute: typeof CanchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eliminar-cuenta': {
      id: '/eliminar-cuenta'
      path: '/eliminar-cuenta'
      fullPath: '/eliminar-cuenta'
      preLoaderRoute: typeof EliminarCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olvide': {
      id: '/olvide'
      path: '/olvide'
      fullPath: '/olvide'
      preLoaderRoute: typeof OlvideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguridad': {
      id: '/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof SeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vivo': {
      id: '/vivo'
      path: '/vivo'
      fullPath: '/vivo'
      preLoaderRoute: typeof VivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CanchaRoute: CanchaRoute,
  ChatRoute: ChatRoute,
  ContactoRoute: ContactoRoute,
  EquipoRoute: EquipoRoute,
  EliminarCuentaRoute: EliminarCuentaRoute,
  LoginRoute: LoginRoute,
  OlvideRoute: OlvideRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetRoute: ResetRoute,
  SeguridadRoute: SeguridadRoute,
  StatsRoute: StatsRoute,
  TerminosRoute: TerminosRoute,
  VivoRoute: VivoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
